### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by GamingIQ** [cdc-sys/level-thumbs-mod#2]
When I installed the mod with geode it said failed to load the mod. Can you give me a reason or please patch this!
![image_2024-03-02_092732961](https://github.com/cdc-sys/level-thumbs-mod/assets/104605959/e933f7b5-af19-4ae8-aa8b-4fd5df1e75a9)

**Comment by cdc-sys** [comment]
press view

**Comment by cdc-sys** [comment]
do what it says to do

**Comment by cdc-sys** [comment]
also that's an outdated version (I think), get the one from releases

**Comment by GamingIQ** [comment]
> also that's an outdated version (I think), get the one from releases


![image_2024-03-02_100404711](https://github.com/cdc-sys/level-thumbs-mod/assets/104605959/85e002be-41a3-46b5-b9e5-af5664a2a157)
 I dont see any instructions?

**Comment by cdc-sys** [comment]
i meant on the "some mods failed to load" thing

**Comment by cdc-sys** [comment]
i meant on the "some mods failed to load" thing
you either don't have node ids or your geode is old.

**Comment by GamingIQ** [comment]
I see the problem now, but Geode hasn't told me there's
![image_2024-03-02_103931063](https://github.com/cdc-sys/level-thumbs-mod/assets/104605959/0a65607d-77e8-4d20-bed8-40fe88019013)
 a new update yet

**Comment by GamingIQ** [comment]
Nvm just had to reinstall geode. Thanks for the help!
