### ISSUE TITLE
Mod fails to load on Geode 3.0.0 on GD 2.206

### ISSUE THREAD

**Issue by yesseruser** [cdc-sys/level-thumbs-mod#22]
Loading the mod on Geode 3.0.0 and GD 2.206 shows error:
```
This mod was created for a different version of GD (2.205). You currently have 2.206.
```

**Comment by ItsSpark-idk** [comment]
cdc didn't port the mod to 2.206, as stated in the level thumbs discord server he spilled peach juice on his laptop and can't code

**Comment by yesseruser** [comment]
This was fixed in the latest update.
