### ISSUE TITLE
The game randomly crash.

### ISSUE THREAD

**Issue by Faisalkhan2266** [cdc-sys/level-thumbs-mod#4]
Whenever the thumbnail Mod is enabled. The game keeps crashing after 5 minutes of playing Geometry Dash. 

Mobile device: Samsung Galaxy S22
Platform: Android 14.

**Comment by cdc-sys** [comment]
provide a crashlog 💀

**Comment by sheepdotcom** [comment]
I had this EXACT issue, it was google translate mod for me

**Comment by Faisalkhan2266** [comment]
This issue is resolved randomly with 1.0.2

**Comment by cdc-sys** [comment]
ok
