### ISSUE TITLE
It would be great to be able to store a cache for thumbnails.

### ISSUE THREAD

**Issue by QSSharky** [cdc-sys/level-thumbs-mod#7]
By storing a cache I mean the following: The first time you see a level with a thumbnail, the thumbnail is downloaded normally, and then the cache of the thumbnail is saved, so you don't have to re-download the thumbnail the next time.

This feature will significantly speed up the download of already saved thumbnails and speed up the work of the game together with the mod.

**Comment by cdc-sys** [comment]
i think I'm gonna make it so thumbnails are only loaded once per session so you have to restart the Game to clear the cache

**Comment by QSSharky** [comment]
That's a great idea. You could also make them load by default once per session, and in the mod settings you could choose whether to save them locally or delete them after the session ends.
